[package]
name = "animals"
version = "0.1.0"
authors = ["Ryan Rampersad <ryan.rampersad@daugherty.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
